# file      : tests/buildfile
# license   : MIT; see accompanying LICENSE file

define common: file
common{*}: extension = testscript

commons = git-common git-pre-commit-common

./: testscript{* -{$commons}} common{$commons}

testscript{git-pre-commit}@./: $git_pre_commit
{
  test = $git_pre_commit
}

testscript{git-pre-commit-version-check}@./: $git_pre_commit_version_check
{
  test = $git_pre_commit_version_check
}

testscript{git-pre-commit-copyright-check}@./: $git_pre_commit_copyright_check
{
  test = $git_pre_commit_copyright_check
}
